"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-14 08:34:12.026994

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=320), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_audit_events_entity", ["entity_type", "entity_id"], unique=False
        )

    op.create_table(
        "licences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product", sa.String(length=200), nullable=False),
        sa.Column("seats_total", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "seats_total >= 0", name=op.f("ck_licences_seats_total_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_licences")),
        sa.UniqueConstraint("product", name=op.f("uq_licences_product")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "inactive",
                name="user_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("licence_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["licence_id"],
            ["licences.id"],
            name=op.f("fk_assignments_licence_id_licences"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_assignments_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignments")),
    )
    with op.batch_alter_table("assignments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assignments_licence_id"), ["licence_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_assignments_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "uq_assignments_active_user_licence",
            ["user_id", "licence_id"],
            unique=True,
            sqlite_where=sa.text("revoked_at IS NULL"),
            postgresql_where=sa.text("revoked_at IS NULL"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assignments", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_assignments_active_user_licence",
            sqlite_where=sa.text("revoked_at IS NULL"),
            postgresql_where=sa.text("revoked_at IS NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_assignments_user_id"))
        batch_op.drop_index(batch_op.f("ix_assignments_licence_id"))

    op.drop_table("assignments")
    op.drop_table("users")
    op.drop_table("licences")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_events_entity")
        batch_op.drop_index(batch_op.f("ix_audit_events_created_at"))

    op.drop_table("audit_events")
    # ### end Alembic commands ###
