"""agent runs and tool calls

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 19:50:04.099444

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("requesting_actor", sa.String(length=320), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "resolved",
                "executing",
                "verifying",
                "completed",
                "needs_clarification",
                "blocked",
                "failed",
                name="agent_run_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "goal_type",
            sa.Enum(
                "ensure_assignment",
                name="agent_goal_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "desired_state",
            sa.Enum(
                "assigned",
                name="agent_desired_state",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("extracted_user_email", sa.Text(), nullable=False),
        sa.Column("extracted_product", sa.Text(), nullable=False),
        sa.Column("resolved_user_id", sa.Integer(), nullable=True),
        sa.Column("resolved_licence_id", sa.Integer(), nullable=True),
        sa.Column(
            "outcome_reason",
            sa.Enum(
                "goal_satisfied",
                "already_satisfied",
                "invalid_input",
                "user_not_found",
                "licence_not_found",
                "licence_ambiguous",
                "no_seats_available",
                "user_inactive",
                "goal_scope_violation",
                "tool_failed",
                "verification_failed",
                "unexpected_error",
                name="agent_outcome_reason",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("outcome_detail", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(completed_at IS NULL) = "
            "(status IN ('received', 'resolved', 'executing', 'verifying'))",
            name=op.f("ck_agent_runs_completed_at_iff_terminal"),
        ),
        sa.CheckConstraint(
            "(status IN ('received', 'resolved', 'executing', 'verifying') "
            "AND outcome_reason IS NULL) "
            "OR (outcome_reason IS NOT NULL AND ("
            "(status = 'completed' "
            "AND outcome_reason IN ('goal_satisfied', 'already_satisfied')) "
            "OR (status = 'needs_clarification' AND outcome_reason IN "
            "('invalid_input', 'user_not_found', 'licence_not_found', "
            "'licence_ambiguous')) "
            "OR (status = 'blocked' "
            "AND outcome_reason IN ('no_seats_available', 'user_inactive')) "
            "OR (status = 'failed' AND outcome_reason IN ('goal_scope_violation', "
            "'tool_failed', 'verification_failed', 'unexpected_error'))))",
            name=op.f("ck_agent_runs_outcome_matches_status"),
        ),
        sa.CheckConstraint(
            "(status IN ('resolved', 'executing', 'verifying', 'completed', "
            "'blocked') AND resolved_user_id IS NOT NULL) "
            "OR (status IN ('received', 'needs_clarification') "
            "AND resolved_user_id IS NULL) "
            "OR status = 'failed'",
            name=op.f("ck_agent_runs_resolved_ids_match_status"),
        ),
        sa.CheckConstraint(
            "(resolved_user_id IS NULL) = (resolved_licence_id IS NULL)",
            name=op.f("ck_agent_runs_resolved_ids_together"),
        ),
        sa.ForeignKeyConstraint(
            ["resolved_licence_id"],
            ["licences.id"],
            name=op.f("fk_agent_runs_resolved_licence_id_licences"),
        ),
        sa.ForeignKeyConstraint(
            ["resolved_user_id"],
            ["users.id"],
            name=op.f("fk_agent_runs_resolved_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_run_id", sa.Integer(), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("arguments", sa.JSON(none_as_null=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "started",
                "succeeded",
                "failed",
                name="tool_call_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("error", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'started' AND completed_at IS NULL "
            "AND result IS NULL AND error IS NULL) "
            "OR (status = 'succeeded' AND completed_at IS NOT NULL "
            "AND result IS NOT NULL AND error IS NULL) "
            "OR (status = 'failed' AND completed_at IS NOT NULL "
            "AND result IS NULL AND error IS NOT NULL)",
            name=op.f("ck_tool_calls_outcome_matches_status"),
        ),
        sa.CheckConstraint(
            "sequence_no >= 1", name=op.f("ck_tool_calls_sequence_no_positive")
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_tool_calls_agent_run_id_agent_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
        sa.UniqueConstraint(
            "agent_run_id",
            "sequence_no",
            name=op.f("uq_tool_calls_agent_run_id_sequence_no"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tool_calls")
    op.drop_table("agent_runs")
    # ### end Alembic commands ###
